import type { Metadata } from "next";
import "../styles/globals.css";
import ClientWrapper from "./ClientWrapper";

export const metadata: Metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode}>) {

  return (
    <html lang="en">
      <body>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
